---
# tasks file for docker

- name: install dependencies
  apt:
    package:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: get LSB release
  ansible.builtin.command:
    cmd: lsb_release -cs
  register: lsb_release
  changed_when: false
  failed_when: lsb_release.rc > 0

- name: Print LSB release info
  debug:
    msg: "{{ lsb_release.stdout }}"

- name: Add Docker apt key
  apt_key: 
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: yes

- name: Install docker repo
  apt_repository: 
    repo: "deb https://download.docker.com/linux/debian {{ lsb_release.stdout }} stable"
    state: present 
    filename: docker 
    update_cache: yes
  become: yes
  
- name: Install docker
  apt:
    package: 
      - docker-ce 
      - docker-ce-cli
      - containerd.io
  become: yes    
