---
# tasks file for docker

- name: install dependencies
  apt:
    package:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
  become: yes

- name: get LSB release
  ansible.builtin.command:
    cmd: lsb_release -cs
  register: lsb_release
  changed_when: false
  failed_when: lsb_release.rc > 0

- name: Print LSB release info
  debug:
    msg: "{{ lsb_release.stdout }}"

- name: check if GPG file exists
  stat:
    path: /usr/share/keyrings/docker-archive-keyring.gpg
  register: gpg

- name: download GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: "/tmp/docker-gpg-key-temp"
  register: gpg_download


- name: debug
  debug:
    msg: "{{ gpg_download }}"

- name: Install GPG key
  ansible.builtin.shell:
    cmd: |
      gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg "{{ gpg_download.dest }}"
  when: gpg.stat.exists == False
  become: yes

#Not ideal long term, ok for now
- name: Install repo
  ansible.builtin.script:
    cmd: installrepo.sh
  become: yes

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  
- name: Install docker
  apt:
    package: 
      - docker-ce 
      - docker-ce-cli
      - containerd.io
  become: yes    
